Bondarenko Tanya's HW-create-annotation
tbondare/jv-create-annotation pull request #1
Opened 2021-01-08 15:15 UTC by tbondare

2021-01-08 18:49 UTC, ivlytvynets requested changes

2021-01-08 18:49 UTC, ivlytvynets commented on src/main/java/dao/HorseDao.java
> +    void changeName(Horse horse, String newName);
here you should have methods that allow you to add object of class to the database (storage) and get objects from storage

2021-01-08 18:49 UTC, ivlytvynets commented on src/main/java/bd/Storage.java
> +    public static final List<Bet> bets = new ArrayList<>();
`
```suggestion
    public static final List<Bet> bets = new ArrayList<>();
    public static final List<Horse> horses = new ArrayList<>();
```

2021-01-11 14:37 UTC, Sofasmile commented on src/main/java/controller/ConsoleHandler.java
> +    HorseDao horseDao = new HorseDaoImpl();
варто додати модифікатори доступу

2021-01-11 14:37 UTC, Sofasmile commented on src/main/java/controller/ConsoleHandler.java
> +            if (consoleInput.equals("q")) {
краще винести "q" в константу

2021-01-11 14:37 UTC, Sofasmile commented on src/main/java/controller/ConsoleHandler.java
> +                        .map(Horse::getName).distinct().collect(Collectors.toList()).toString());
давай видалимо тут System.out.println

2021-01-11 14:37 UTC, Sofasmile commented on src/main/java/controller/ConsoleHandler.java
> +    private void horseDataProcessing(String nameHorse, Scanner scanner) {
цей метод загалом можна видалити. Давай в нас не буде логіки зміни імені для Horse
ми просто все будемо обробляти в методі handler() і там буде створювати об'єкт ставки і об'єкт коня

2021-01-11 14:37 UTC, Sofasmile commented on src/main/java/controller/ConsoleHandler.java
> +        Storage.bets.addAll(betDao.getAll());
замість  Storage в цьому класі можна використовувати методи betDao

2021-01-11 14:37 UTC, Sofasmile commented on src/main/java/model/Horse.java
> +    String name;
модифікатор

2021-01-11 15:17 UTC, Sofasmile approved these changes
можеш мержити цей ПР і приступати до наступної домашки)

2021-01-11 15:24 UTC, merged